@startuml
package Drone {
    [Drone (RobomasterTT)]
}

package Backend {
    package SDK {
        [Raw Udp Socket] <--> [ActionManager] : packets
    }
    [LiveRoutes] --> [ActionManager]
    [Websocket] <--> [ActionManager] : status

    package Video {
        [FFmpeg] --> [MediaMTX] : video
    }

    package Ai {
        [MediaMTX] --> [OpenCV Receiver] : video
        [OpenCV Receiver] --> [YOLO]
        [YOLO] --> [Ai] : people
        [OpenCV Receiver] --> [Ring detection]
        [Ring detection] --> [Ai] : rings
        [Ring detection] --> [Ring follower]
        [Ring follower] --> [ActionManager]
        [Ai] --> [Websocket]
    }
}



package Frontend {
    [VideoStream]
    [Telemetry]
    [Pathmap]
    [Flight-Control]
    [Led-Editor]
}

[Drone (RobomasterTT)] <..> [Raw Udp Socket] : status & commands
[Drone (RobomasterTT)] ..> [FFmpeg] : video

[VideoStream] <.. [MediaMTX] : video (WebRTC)
[Telemetry] <.. [Websocket] : telemetry
[Flight-Control] ..> [LiveRoutes] : flight-control
[Led-Editor] ..> [LiveRoutes] : led
[Pathmap] <.. [Telemetry] : path
@enduml